collection: appleApps
k: 8
classifiers:
  - "facebook/bart-large-mnli"
  - "roberta-large-mnli"
  - "valhalla/distilbart-mnli-12-9"
keywords:
  - cannabis
  - marijuana
  - hemp
  - weed
  - dispensary
output_prefix: img/appleApps
